# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuickLayer
                                 A QGIS plugin
 Switch between the images of your choice using shortcuts
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-11
        copyright            : (C) 2021 by João P. Bueno
        email                : jo.bueno98@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QuickLayer class from file QuickLayer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .quick_layer import QuickLayer
    return QuickLayer(iface)
